### ISSUE TITLE
Files otherwise ignored by .rubocop.yml are still linted

### ISSUE THREAD

**Issue by timriley** [ashfurrow/danger-rubocop#6]
I've configured a `.rubocop.yml` for my project to ignore some directories:

``` yaml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
```

However, with the way the danger plugin invokes rubocop, explicitly passing a list of changed files from the PR, the behaviour of rubocop is to check those files for violations even if they've been ignored in the `.rubocop.yml` config (whose `Exclude` options only seem to apply if you're running it for whole directories or all files in the project).

Do you have any thoughts about how this might be made a little nicer?
